"""add_account_identifier_fields

Revision ID: 96f1a1b6c577
Revises: dbd478af76d0
Create Date: 2026-01-05 07:52:00.244552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f1a1b6c577'
down_revision: Union[str, Sequence[str], None] = 'dbd478af76d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_holder', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_bank_account', ['bank_type', 'account_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bank_account', type_='unique')
        batch_op.drop_column('account_holder')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
