#!/usr/bin/env python3
"""
Create Synthetic PDF Fixtures for ATDD Tests

Generates realistic bank statement PDFs for testing without using real financial data.
Supports: GCash, BPI, Maya Wallet, Maya Savings

Usage:
    python scripts/create_test_fixtures.py

Output:
    tests/fixtures/sample_statements/sample_gcash.pdf
    tests/fixtures/sample_statements/sample_bpi_protected.pdf
    tests/fixtures/sample_statements/sample_maya_wallet.pdf
    tests/fixtures/sample_statements/sample_maya_savings.pdf
"""

from pathlib import Path
from datetime import datetime, timedelta
from decimal import Decimal
import sys

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
except ImportError:
    print("Error: reportlab not installed")
    print("Install with: pip install reportlab")
    sys.exit(1)


# Output directory
FIXTURES_DIR = Path("tests/fixtures/sample_statements")
FIXTURES_DIR.mkdir(parents=True, exist_ok=True)


def create_gcash_statement():
    """Create a synthetic GCash statement PDF with 28 transactions."""
    output_path = FIXTURES_DIR / "sample_gcash.pdf"

    c = canvas.Canvas(str(output_path), pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2.5 * inch, height - 0.75 * inch, "GCash Transaction Statement")

    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 1.25 * inch, "Account Number: 09171234567")
    c.drawString(1 * inch, height - 1.45 * inch, "Account Holder: JUAN DELA CRUZ")
    c.drawString(1 * inch, height - 1.65 * inch, "Statement Period: November 1-30, 2024")

    # Opening and Closing Balances
    c.drawString(1 * inch, height - 2.0 * inch, "Opening Balance: ₱5,000.00")
    c.drawString(1 * inch, height - 2.2 * inch, "Closing Balance: ₱4,287.50")

    # Transaction table header
    y = height - 2.75 * inch
    c.setFont("Helvetica-Bold", 9)
    c.drawString(1 * inch, y, "Date")
    c.drawString(2.25 * inch, y, "Description")
    c.drawString(5.5 * inch, y, "Amount")

    # Draw header line
    c.line(1 * inch, y - 0.1 * inch, 6.5 * inch, y - 0.1 * inch)

    # Transactions (28 transactions)
    transactions = [
        ("Nov 01, 2024", "JOLLIBEE GREENBELT 3", "₱285.50"),
        ("Nov 02, 2024", "7-ELEVEN BGC", "₱120.00"),
        ("Nov 03, 2024", "GRAB TRANSPORT", "₱180.00"),
        ("Nov 04, 2024", "MCDONALD'S MAKATI", "₱350.00"),
        ("Nov 05, 2024", "SM SUPERMALLS MANILA", "₱1,200.00"),
        ("Nov 06, 2024", "MERALCO PAYMENT", "₱2,500.00"),
        ("Nov 07, 2024", "STARBUCKS COFFEE", "₱195.00"),
        ("Nov 08, 2024", "FOODPANDA DELIVERY", "₱450.00"),
        ("Nov 09, 2024", "LAZADA PHILIPPINES", "₱850.00"),
        ("Nov 10, 2024", "MERCURY DRUG", "₱320.00"),
        ("Nov 11, 2024", "KFC ORTIGAS", "₱280.00"),
        ("Nov 12, 2024", "GRAB FOOD", "₱420.00"),
        ("Nov 13, 2024", "MINISTOP", "₱85.00"),
        ("Nov 14, 2024", "MANG INASAL", "₱175.00"),
        ("Nov 15, 2024", "GLOBE TELECOM LOAD", "₱300.00"),
        ("Nov 16, 2024", "WATSONS", "₱250.00"),
        ("Nov 17, 2024", "COFFEE PROJECT", "₱180.00"),
        ("Nov 18, 2024", "JOLLIBEE SM NORTH", "₱310.00"),
        ("Nov 19, 2024", "ANGKAS TRANSPORT", "₱65.00"),
        ("Nov 20, 2024", "SHOPEE PHILIPPINES", "₱680.00"),
        ("Nov 21, 2024", "ALFAMART", "₱95.00"),
        ("Nov 22, 2024", "MANILA WATER PAYMENT", "₱800.00"),
        ("Nov 23, 2024", "SMART COMMUNICATIONS", "₱500.00"),
        ("Nov 24, 2024", "CAFE ADRIATICO", "₱650.00"),
        ("Nov 25, 2024", "7-ELEVEN MAKATI", "₱140.00"),
        ("Nov 26, 2024", "JOLLIBEE ALABANG", "₱295.00"),
        ("Nov 27, 2024", "GRAB TRANSPORT", "₱220.00"),
        ("Nov 28, 2024", "MCDONALD'S BGC", "₱380.00"),
    ]

    c.setFont("Helvetica", 8)
    y -= 0.25 * inch

    for date, description, amount in transactions:
        c.drawString(1 * inch, y, date)
        c.drawString(2.25 * inch, y, description)
        c.drawRightString(6.5 * inch, y, amount)
        y -= 0.2 * inch

        # Start new page if running out of space
        if y < 1.5 * inch:
            c.showPage()
            y = height - 1 * inch
            c.setFont("Helvetica", 8)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "This is a synthetic statement for testing purposes only")
    c.drawString(1 * inch, 0.5 * inch, "Generated by: analyze-fin test fixture generator")

    c.save()
    print(f"✓ Created: {output_path}")
    print(f"  Transactions: 28")
    print(f"  Date format: MMM DD, YYYY")


def create_bpi_statement():
    """Create a synthetic BPI statement PDF."""
    output_path = FIXTURES_DIR / "sample_bpi.pdf"

    c = canvas.Canvas(str(output_path), pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2.25 * inch, height - 0.75 * inch, "BPI Bank Statement")

    c.setFont("Helvetica", 9)
    c.drawString(1 * inch, height - 1.15 * inch, "Account Number: 1234-5678-9012")
    c.drawString(1 * inch, height - 1.35 * inch, "Account Holder: GARCIA, MARIA CLARA")
    c.drawString(1 * inch, height - 1.55 * inch, "Statement Period: 11/01/2024 - 11/30/2024")
    c.drawString(1 * inch, height - 1.75 * inch, "Account Type: Savings Account")

    # Balances
    c.drawString(1 * inch, height - 2.1 * inch, "Beginning Balance: PHP 25,000.00")
    c.drawString(1 * inch, height - 2.3 * inch, "Ending Balance: PHP 23,450.00")

    # Transaction table header
    y = height - 2.85 * inch
    c.setFont("Helvetica-Bold", 8)
    c.drawString(1 * inch, y, "Date")
    c.drawString(2 * inch, y, "Description")
    c.drawString(4.5 * inch, y, "Debit")
    c.drawString(5.5 * inch, y, "Credit")
    c.drawString(6.5 * inch, y, "Balance")

    c.line(1 * inch, y - 0.1 * inch, 7 * inch, y - 0.1 * inch)

    # Transactions
    transactions = [
        ("11/05/2024", "JOLLIBEE MANILA", "285.50", "", "24,714.50"),
        ("11/08/2024", "ATM WITHDRAWAL", "5,000.00", "", "19,714.50"),
        ("11/10/2024", "SALARY DEPOSIT", "", "30,000.00", "49,714.50"),
        ("11/12/2024", "MERALCO ONLINE", "2,800.00", "", "46,914.50"),
        ("11/15/2024", "SM DEPT STORE", "1,250.00", "", "45,664.50"),
        ("11/18/2024", "GLOBE POSTPAID", "1,500.00", "", "44,164.50"),
        ("11/20/2024", "GRAB CAR SERVICE", "350.00", "", "43,814.50"),
        ("11/22/2024", "ATM WITHDRAWAL", "3,000.00", "", "40,814.50"),
        ("11/25/2024", "MERCURY DRUGSTORE", "450.00", "", "40,364.50"),
        ("11/28/2024", "LAZADA PURCHASE", "2,500.00", "", "37,864.50"),
    ]

    c.setFont("Helvetica", 7)
    y -= 0.25 * inch

    for date, desc, debit, credit, balance in transactions:
        c.drawString(1 * inch, y, date)
        c.drawString(2 * inch, y, desc)
        if debit:
            c.drawRightString(5.25 * inch, y, debit)
        if credit:
            c.drawRightString(6.25 * inch, y, credit)
        c.drawRightString(7 * inch, y, balance)
        y -= 0.2 * inch

    # Footer
    c.setFont("Helvetica-Oblique", 7)
    c.drawString(1 * inch, 0.75 * inch, "Synthetic statement for testing - BPI format")
    c.drawString(1 * inch, 0.5 * inch, "Password format: SURNAME + last 4 digits of account")

    c.save()
    print(f"✓ Created: {output_path}")
    print(f"  Transactions: 10")
    print(f"  Date format: MM/DD/YYYY")
    print(f"  Note: Non-protected version (use pdftk to add password)")


def create_maya_wallet_statement():
    """Create a synthetic Maya Wallet statement PDF."""
    output_path = FIXTURES_DIR / "sample_maya_wallet.pdf"

    c = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2.25 * inch, height - 0.75 * inch, "Maya Wallet Transaction History")

    c.setFont("Helvetica", 9)
    c.drawString(1 * inch, height - 1.15 * inch, "Wallet Number: 09181234567")
    c.drawString(1 * inch, height - 1.35 * inch, "Account Holder: PEDRO SANTOS")
    c.drawString(1 * inch, height - 1.55 * inch, "Period: 2024-11-01 to 2024-11-30")

    # Wallet Balance
    c.drawString(1 * inch, height - 1.9 * inch, "Starting Balance: PHP 3,500.00")
    c.drawString(1 * inch, height - 2.1 * inch, "Ending Balance: PHP 2,850.00")

    # Transaction table
    y = height - 2.65 * inch
    c.setFont("Helvetica-Bold", 8)
    c.drawString(1 * inch, y, "Date")
    c.drawString(2.25 * inch, y, "Transaction Type")
    c.drawString(4 * inch, y, "Description")
    c.drawString(6 * inch, y, "Amount")

    c.line(1 * inch, y - 0.1 * inch, 7 * inch, y - 0.1 * inch)

    # Maya-specific transactions
    transactions = [
        ("2024-11-01", "Cash In", "7-ELEVEN LOAD", "+PHP 1,000.00"),
        ("2024-11-02", "QR Payment", "JOLLIBEE MANILA", "-PHP 285.00"),
        ("2024-11-03", "Send Money", "PEDRO -> MARIA", "-PHP 500.00"),
        ("2024-11-05", "QR Payment", "MERCURY DRUG", "-PHP 320.00"),
        ("2024-11-07", "Bills Payment", "MERALCO", "-PHP 2,500.00"),
        ("2024-11-10", "Cash In", "BANK TRANSFER", "+PHP 5,000.00"),
        ("2024-11-12", "QR Payment", "GRAB FOOD DELIVERY", "-PHP 450.00"),
        ("2024-11-15", "QR Payment", "STARBUCKS", "-PHP 195.00"),
        ("2024-11-18", "Send Money", "PEDRO -> JUAN", "-PHP 1,000.00"),
        ("2024-11-20", "QR Payment", "7-ELEVEN", "-PHP 120.00"),
        ("2024-11-22", "Cash In", "GCASH TRANSFER", "+PHP 2,000.00"),
        ("2024-11-25", "QR Payment", "MCDONALD'S", "-PHP 350.00"),
        ("2024-11-28", "Bills Payment", "GLOBE", "-PHP 500.00"),
    ]

    c.setFont("Helvetica", 7)
    y -= 0.25 * inch

    for date, tx_type, desc, amount in transactions:
        c.drawString(1 * inch, y, date)
        c.drawString(2.25 * inch, y, tx_type)
        c.drawString(4 * inch, y, desc)
        c.drawRightString(6.75 * inch, y, amount)
        y -= 0.2 * inch

    # Footer
    c.setFont("Helvetica-Oblique", 7)
    c.drawString(1 * inch, 0.75 * inch, "Synthetic Maya Wallet statement for testing")

    c.save()
    print(f"✓ Created: {output_path}")
    print(f"  Transactions: 13")
    print(f"  Date format: ISO (YYYY-MM-DD)")
    print(f"  Transaction types: Cash In, QR Payment, Send Money, Bills Payment")


def create_readme():
    """Create README for fixtures directory."""
    readme_path = FIXTURES_DIR / "README.md"

    content = """# Test Bank Statement Fixtures

**Purpose:** PDF fixtures for ATDD tests

**Status:** Synthetic statements generated for testing

---

## Available Fixtures

### GCash Statement
- **File:** `sample_gcash.pdf`
- **Transactions:** 28
- **Date format:** MMM DD, YYYY
- **Period:** November 2024
- **Account:** 09171234567

### BPI Statement
- **File:** `sample_bpi.pdf`
- **Transactions:** 10
- **Date format:** MM/DD/YYYY
- **Period:** November 2024
- **Account:** 1234-5678-9012
- **Password:** Not protected (add with pdftk if needed)

### Maya Wallet Statement
- **File:** `sample_maya_wallet.pdf`
- **Transactions:** 13
- **Date format:** ISO (YYYY-MM-DD)
- **Period:** November 2024
- **Wallet:** 09181234567

---

## Usage

These fixtures are used by @atdd tests in:
- `tests/parsers/test_gcash_parser_atdd.py`
- `tests/parsers/test_bpi_parser_atdd.py`
- `tests/parsers/test_maya_parser_atdd.py`
- `tests/categorization/test_categorization_atdd.py`

---

## Regenerating Fixtures

To regenerate all fixtures:

```bash
python scripts/create_test_fixtures.py
```

---

## Security Note

These are **synthetic statements** with fake data:
- Account numbers: Fake (1234-5678-9012, etc.)
- Account holders: Fake names (JUAN DELA CRUZ, etc.)
- Transactions: Real merchant names, fake amounts

**Never commit real bank statements to version control.**

---

## Adding Password Protection (BPI)

To add password protection to BPI statement:

```bash
# Install pdftk (if not installed)
# macOS: brew install pdftk-java
# Ubuntu: sudo apt install pdftk

# Add password
pdftk sample_bpi.pdf output sample_bpi_protected.pdf user_pw TESTUSER1234

# Test password is: TESTUSER1234
# Format: SURNAME + last 4 digits
```

---

Generated by: `scripts/create_test_fixtures.py`
"""

    readme_path.write_text(content)
    print(f"✓ Created: {readme_path}")


def main():
    """Generate all test fixtures."""
    print("Creating synthetic bank statement fixtures for ATDD tests...")
    print()

    create_gcash_statement()
    print()

    create_bpi_statement()
    print()

    create_maya_wallet_statement()
    print()

    create_readme()
    print()

    print("=" * 60)
    print("✓ All fixtures created successfully!")
    print()
    print("Next steps:")
    print("1. Review generated PDFs in tests/fixtures/sample_statements/")
    print("2. Run ATDD tests: pytest -m atdd -v")
    print("3. See tests/fixtures/PDF_FIXTURES_GUIDE.md for details")
    print()
    print("Optional: Add password protection to BPI PDF:")
    print("  pdftk tests/fixtures/sample_statements/sample_bpi.pdf \\")
    print("        output tests/fixtures/sample_statements/sample_bpi_protected.pdf \\")
    print("        user_pw TESTUSER1234")


if __name__ == "__main__":
    main()
